name: Deploy Astro Site

on:
  push:
    branches:
      - astro # Change this to your main branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # Change this to the desired Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Move build files to docs folder
        run: mv dist docs

      - name: Deploy to hosting provider
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
